## Matrix:
A two-dimensional array of numbers, consisting of multiple rows and columns.

In [1]:
import numpy as np

### Creating Matrix Using Numpy

In [2]:
matrix1 = np.array([[2,3],[4,2]])
print(matrix1)

[[2 3]
 [4 2]]


In [3]:
#Shape of matrix
matrix1.shape

(2, 2)

### Creating Matrices with Random Values

In [4]:
random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.9190716  0.40656564 0.62541346]
 [0.73899551 0.5545155  0.1118278 ]
 [0.02779252 0.56966287 0.41482583]]


It gives us decimals less than 1

In [5]:
# creating matrix with random integers
random_integer_matrix = np.random.randint(100, size = (4,5))
print(random_integer_matrix)

[[25  4 42 61  9]
 [90 74 88 94 71]
 [56 60 88 25 30]
 [40 17 57  8 75]]


### Creating Matrix with all values as 1

In [6]:
matrix_ones = np.ones((3,3))
print(matrix_ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


It gives us decimals

In [7]:
#creating matrix with integer values
matrix_ones_int = np.ones((7,7), dtype = int)
print(matrix_ones_int)

[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]


### Creating Null Matrix or Zero Matrix

In [8]:
null_matrix = np.zeros((3,3))
print(null_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Creating Identity Matrix

In [9]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Transpose of a Matrix

In [10]:
# matrix with random integer values
a = np.random.randint(10, size = (3,6))
transpose_a = np.transpose(a)
print(a)
print(transpose_a)

[[1 1 7 7 4 5]
 [5 3 1 1 8 2]
 [8 1 6 2 4 5]]
[[1 5 8]
 [1 3 1]
 [7 1 6]
 [7 1 2]
 [4 8 4]
 [5 2 5]]


### Matrix Addition

Two Matrices can be added only if they have same shape.

In [11]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(A+B)

[[ 6  8]
 [10 12]]


We get error if the shape is not same.

In [23]:
a = np.random.randint(10, size=(3,3))
b = np.random.randint(20, size=(3,4))
print(a+b)

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

### Matrix Subtraction

Two Matrices can be subtracted only if they have same shape.

In [12]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(A-B)

[[-4 -4]
 [-4 -4]]


We get error if the shape is not same.

In [24]:
a = np.random.randint(10, size=(3,3))
b = np.random.randint(20, size=(3,4))
print(a-b)

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

### Multiplying a matrix by a scalar

In [13]:
x = 5
y = np.random.randint(10, size = (3,3))
product = np.multiply(x,y)
print(product)

[[30 40  0]
 [30  0 40]
 [15 15 25]]


In [14]:
product1 = x*y
print(product1)

[[30 40  0]
 [30  0 40]
 [15 15 25]]


### Multiplying two matrices

The number of columns in first matrix should be equal to number of rows in second matrix.

In [20]:
matrix1 = np.random.randint(5, size=(3,3))
matrix2 = np.random.randint(5, size=(3,4))
print(matrix1)
print(matrix2)

[[4 1 2]
 [1 3 1]
 [4 4 0]]
[[3 3 1 1]
 [0 0 3 1]
 [0 0 1 2]]


In [21]:
product = np.dot(matrix1, matrix2)
print(product)

[[12 12  9  9]
 [ 3  3 11  6]
 [12 12 16  8]]


The resultant have same number of rows in first matrix and same number of columns in second matrix.

In [16]:
product.shape

(3, 4)

Error if the number of columns in first matrix and number of rows in second matrix are not equal.

In [26]:
matrix1 = np.random.randint(5, size=(3,3))
matrix2 = np.random.randint(5, size=(4,4))
product = np.dot(matrix1, matrix2)

ValueError: shapes (3,3) and (4,4) not aligned: 3 (dim 1) != 4 (dim 0)

### Element wise Matrix Multiplication

In [18]:
matrix1 = np.random.randint(5, size=(3,3))
matrix2 = np.random.randint(5, size=(3,3))
print(matrix1)
print(matrix2)

[[1 3 4]
 [4 0 3]
 [1 2 2]]
[[1 3 2]
 [4 1 2]
 [1 1 0]]


In [19]:
product = np.multiply(matrix1, matrix2)
print(product)

[[ 1  9  8]
 [16  0  6]
 [ 1  2  0]]


We get error if the shape is not same.

In [27]:
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,4))
product = np.multiply(matrix_3, matrix_4)

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 